apiVersion: v1
kind: Service
metadata:
  name: drug-discovery-backend
  namespace: drug-discovery
spec:
  selector:
    app: drug-discovery-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP

