apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: market-valuation-ingress
  namespace: market-valuation
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts: ["market_valuation.quasim.example.com"]
      secretName: market-valuation-tls
  rules:
    - host: market_valuation.quasim.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: market-valuation-backend
                port:
                  number: 80

