apiVersion: v1
kind: Service
metadata:
  name: market-valuation-backend
  namespace: market-valuation
spec:
  selector:
    app: market-valuation-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP

