apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/namespaces.yaml
  - ../../base/resource-quotas.yaml
  - ../../base/network-policies.yaml
patches:
  - path: patches/quotas-patch.yaml
  - path: patches/np-patch.yaml
