apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8snonroot
spec:
  crd:
    spec:
      names:
        kind: K8sNonRoot
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8snonroot
      violation[{
        "msg": msg,
      }] {
        input.review.object.spec.containers[_].securityContext.runAsNonRoot != true
        msg := "Containers must runAsNonRoot=true"
      }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sNonRoot
metadata:
  name: require-nonroot
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
