apiVersion: v1
kind: Service
metadata:
  name: quantum-benchmarks-backend
  namespace: quantum-benchmarks
spec:
  selector:
    app: quantum-benchmarks-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP

