apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telecom-networks-ingress
  namespace: telecom-networks
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts: ["telecom_networks.quasim.example.com"]
      secretName: telecom-networks-tls
  rules:
    - host: telecom_networks.quasim.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: telecom-networks-backend
                port:
                  number: 80

