apiVersion: v1
kind: Service
metadata:
  name: telecom-networks-backend
  namespace: telecom-networks
spec:
  selector:
    app: telecom-networks-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP

