apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: supply-chain-ingress
  namespace: supply-chain
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts: ["supply_chain.quasim.example.com"]
      secretName: supply-chain-tls
  rules:
    - host: supply_chain.quasim.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: supply-chain-backend
                port:
                  number: 80

