apiVersion: v1
kind: Service
metadata:
  name: supply-chain-backend
  namespace: supply-chain
spec:
  selector:
    app: supply-chain-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP

