apiVersion: v1
kind: Service
metadata:
  name: healthcare-analytics-backend
  namespace: healthcare-analytics
spec:
  selector:
    app: healthcare-analytics-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP

