apiVersion: v1
kind: Service
metadata:
  name: finance-trading-backend
  namespace: finance-trading
spec:
  selector:
    app: finance-trading-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP

