apiVersion: v1
kind: Service
metadata:
  name: autonomous-systems-backend
  namespace: autonomous-systems
spec:
  selector:
    app: autonomous-systems-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
