apiVersion: v1
kind: Service
metadata:
  name: optimization-services-backend
  namespace: optimization-services
spec:
  selector:
    app: optimization-services-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP

