apiVersion: v1
kind: Service
metadata:
  name: cryptography-backend
  namespace: cryptography
spec:
  selector:
    app: cryptography-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP

